development:
  adapter: postgresql
  database: sac_development
  host: localhost
  username: postgresql
  password: password

test:
  adapter: postgresql
  database: sac_test
  host: localhost
  username: postgresql
  password: password